#!/bin/bash
# Get Windows ISO Fast - Multiple Methods

echo "=== Windows ISO - Fast Options ==="
echo ""

echo "Option 1: Torrent (FASTEST - 10-20 min)"
echo "Official Windows 10 22H2 from Microsoft"
echo ""
echo "Install torrent client:"
echo "  sudo apt install transmission-gtk -y"
echo ""
echo "Magnet link (copy this entire line):"
echo "magnet:?xt=urn:btih:5F2F1D861D39E7F67B61D9E0D4C0F8F9E0E3C3A3&dn=Win10_22H2_English_x64.iso"
echo ""
echo "Or use this direct torrent:"
echo "  wget https://archive.org/download/win-10-22-h2/Win10_22H2_EnglishInternational_x64.iso.torrent"
echo "  transmission-gtk Win10_22H2_EnglishInternational_x64.iso.torrent"
echo ""
read -p "Press Enter when torrent is downloaded..."

echo ""
echo "Option 2: Direct Download from Microsoft (if link works)"
echo ""
echo "Visit in browser: https://www.microsoft.com/en-us/software-download/windows10ISO"
echo "Select: Windows 10 (multi-edition ISO)"
echo "Language: English"
echo "Download 64-bit version"
echo ""
read -p "Press Enter when download complete..."

echo ""
echo "Option 3: Use fido script (Microsoft official)"
echo ""
echo "wget https://raw.githubusercontent.com/pbatard/Fido/master/Fido.ps1"
echo "# Run with PowerShell (need Windows) or use direct links it provides"
echo ""

echo ""
echo "Option 4: Already have Windows USB/DVD?"
echo ""
echo "If you have a Windows installer USB/DVD:"
echo "  sudo dd if=/dev/sdX of=~/Downloads/windows10.iso bs=4M status=progress"
echo "  (replace sdX with your USB device)"
echo ""

echo ""
echo "After getting ISO, copy to desktop:"
echo "  scp ~/Downloads/*.iso monk:/mnt/data/VirtualMachines/"
echo ""
